version: '3.8'
services:

  #servicio de backend
  php:
    container_name: php
    build:
      context: .
      target: php
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
  #servicio de base de datos
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data: ~